import { getAudio } from '@/utils/audioLoader'

const getQuestions = (t: any, language: string) => {
  const audioFiles = getAudio(language)

  return [
    {
      question: t('assessment.questions.q1'),
      questionAudio: audioFiles.question_1,
      questionId: 'question_1',
      answerOptions: [
        {
          label: t('assessment.answers.always'),
          value: '1',
          score: 0,
          image: 'Q1_Always.png',
          audio: audioFiles.question_1_option_1,
        },
        {
          label: t('assessment.answers.never'),
          value: '2',
          score: 0,
          image: 'Q1_Never.png',
          audio: audioFiles.question_1_option_2,
        },
        {
          label: t('assessment.answers.sometimes'),
          value: '3',
          score: 0,
          image: 'Q1_Sometimes.png',
          audio: audioFiles.question_1_option_3,
        },
      ],
      image: '1.png',
    },
    {
      question: t('assessment.questions.q2'),
      questionAudio: audioFiles.question_2,
      questionId: 'question_2',
      answerOptions: [
        {
          label: t('assessment.answers.always'),
          value: '1',
          score: 0,
          image: 'Q2_Always.png',
          audio: audioFiles.question_2_option_1,
        },
        {
          label: t('assessment.answers.never'),
          value: '2',
          score: 0,
          image: 'Q2_Never.png',
          audio: audioFiles.question_2_option_2,
        },
        {
          label: t('assessment.answers.sometimes'),
          value: '3',
          score: 0,
          image: 'Q2_Sometimes.png',
          audio: audioFiles.question_2_option_3,
        },
      ],
      image: '2.png',
    },
    {
      question: t('assessment.questions.q3'),
      questionAudio: audioFiles.question_3,
      questionId: 'question_3',
      answerOptions: [
        {
          label: t('assessment.answers.always'),
          value: '1',
          score: 0,
          image: 'Q3_Always.png',
          audio: audioFiles.question_3_option_1,
        },
        {
          label: t('assessment.answers.never'),
          value: '2',
          score: 0,
          image: 'Q3_Never.png',
          audio: audioFiles.question_3_option_2,
        },
        {
          label: t('assessment.answers.sometimes'),
          value: '3',
          score: 0,
          image: 'Q3_Sometimes.png',
          audio: audioFiles.question_3_option_3,
        },
      ],
      image: '3.png',
    },
    {
      question: t('assessment.questions.q4'),
      type: 'slider',
      questionAudio: audioFiles.question_4,
      questionId: 'question_4',
      answerOptions: [
        {
          label: t('assessment.answers.allTheDays'),
          value: '1',
          score: 0,
          audio: audioFiles.question_4_option_1,
        },
        {
          label: t('assessment.answers.someDays'),
          value: '2',
          score: 0,
          audio: audioFiles.question_4_option_2,
        },
        {
          label: t('assessment.answers.none'),
          value: '3',
          score: 0,
          audio: audioFiles.question_4_option_3,
        },
      ],
      image: '4.png',
    },
    {
      question: t('assessment.questions.q5'),
      questionAudio: audioFiles.question_5,
      questionId: 'question_5',
      answerOptions: [
        {
          label: t('assessment.answers.happy'),
          value: '1',
          image: 'Happy.png',
          score: 1,
          audio: audioFiles.question_5_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '2',
          image: 'Angry.png',
          score: 1,
          audio: audioFiles.question_5_option_2,
        },
        {
          label: t('assessment.answers.sad'),
          value: '3',
          image: 'Sad.png',
          score: 3,
          audio: audioFiles.question_5_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '5.png',
    },
    {
      type: 'story',
      question: t('assessment.stories.s1'),
      questionAudio: audioFiles.story_1,
      image: '6,7,8,9.png',
    },
    {
      question: t('assessment.questions.q6'),
      questionAudio: audioFiles.question_6,
      questionId: 'question_6',
      answerOptions: [
        {
          label: t('assessment.answers.happy'),
          value: '1',
          image: 'Happy.png',
          score: 1,
          audio: audioFiles.question_6_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '2',
          image: 'Angry.png',
          score: 3,
          audio: audioFiles.question_6_option_2,
        },
        {
          label: t('assessment.answers.sad'),
          value: '3',
          image: 'Sad.png',
          score: 3,
          audio: audioFiles.question_6_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_6_option_4,
        },
      ],
      image: '6,7,8,9.png',
    },
    {
      question: t('assessment.questions.q7'),
      questionAudio: audioFiles.question_7,
      questionId: 'question_7',
      answerOptions: [
        {
          label: t('assessment.answers.runningFast'),
          value: '1',
          image: 'Q7_running_fast.png',
          score: 3,
          audio: audioFiles.question_7_option_1,
        },
        {
          label: t('assessment.answers.wantedToHit'),
          value: '2',
          image: 'Q7_wanted_to_hit.png',
          score: 1,
          audio: audioFiles.question_7_option_2,
        },
        {
          label: t('assessment.answers.didNotSee'),
          value: '3',
          image: 'Q7_did_not_see.png',
          score: 3,
          audio: audioFiles.question_7_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_7_option_4,
        },
      ],
      image: '6,7,8,9.png',
    },
    {
      question: t('assessment.questions.q8'),
      questionAudio: audioFiles.question_8,
      questionId: 'question_8',
      answerOptions: [
        {
          label: t('assessment.answers.laugh'),
          value: '1',
          image: 'Q8_Laugh.png',
          score: 1,
          audio: audioFiles.question_8_option_1,
        },
        {
          label: t('assessment.answers.comfort'),
          value: '2',
          image: 'Q8_Comfort.png',
          score: 3,
          audio: audioFiles.question_8_option_2,
        },
        {
          label: t('assessment.answers.walkAway'),
          value: '3',
          image: 'Q8_walk_away.png',
          score: 2,
          audio: audioFiles.question_8_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_8_option_4,
        },
      ],
      image: '6,7,8,9.png',
    },
    {
      question: t('assessment.questions.q9'),
      questionAudio: audioFiles.question_9,
      questionId: 'question_9',
      answerOptions: [
        {
          label: t('assessment.answers.breathe'),
          value: '1',
          image: 'Q9_breathe.png',
          score: 3,
          audio: audioFiles.question_9_option_1,
        },
        {
          label: t('assessment.answers.hit'),
          value: '2',
          image: 'Q9_hit.png',
          score: 1,
          audio: audioFiles.question_9_option_2,
        },
        {
          label: t('assessment.answers.askAdult'),
          value: '3',
          image: 'Q9_ask_adult.png',
          score: 3,
          audio: audioFiles.question_9_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_9_option_4,
        },
      ],
      image: '6,7,8,9.png',
    },
    {
      question: t('assessment.questions.q10'),
      questionAudio: audioFiles.question_10,
      questionId: 'question_10',
      answerOptions: [
        {
          label: t('assessment.answers.happy'),
          value: '1',
          score: 1,
          image: 'Happy.png',
          audio: audioFiles.question_5_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '2',
          score: 3,
          image: 'Angry.png',
          audio: audioFiles.question_5_option_2,
        },
        {
          label: t('assessment.answers.sad'),
          value: '3',
          score: 1,
          image: 'Sad.png',
          audio: audioFiles.question_5_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          score: 1,
          image: 'dont_know.png',
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '6,7,8,9.png',
    },
    {
      type: 'story',
      question: t('assessment.stories.s2'),
      questionAudio: audioFiles.story_2,
      image: '10.png',
    },
    {
      question: t('assessment.questions.q11'),
      questionAudio: audioFiles.question_11,
      questionId: 'question_11',
      answerOptions: [
        {
          label: t('assessment.answers.happy'),
          value: '1',
          score: 1,
          image: 'Happy.png',
          audio: audioFiles.question_5_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '2',
          score: 3,
          image: 'Angry.png',
          audio: audioFiles.question_5_option_2,
        },
        {
          label: t('assessment.answers.sad'),
          value: '3',
          score: 3,
          image: 'Sad.png',
          audio: audioFiles.question_5_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          score: 1,
          image: 'dont_know.png',
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '11,12,13,14.png',
    },
    {
      question: t('assessment.questions.q12'),
      questionAudio: audioFiles.question_12,
      questionId: 'question_12',
      answerOptions: [
        {
          label: t('assessment.answers.mistake'),
          value: '1',
          image: 'Q12_mistake.png',
          score: 3,
          audio: audioFiles.question_12_option_1,
        },
        {
          label: t('assessment.answers.didntLike'),
          value: '2',
          image: 'Q12_didnt_like.png',
          score: 2,
          audio: audioFiles.question_12_option_2,
        },
        {
          label: t('assessment.answers.ruin'),
          value: '3',
          image: 'Q12_ruin.png',
          score: 1,
          audio: audioFiles.question_12_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '11,12,13,14.png',
    },
    {
      question: t('assessment.questions.q13'),
      questionAudio: audioFiles.question_13,
      questionId: 'question_13',
      answerOptions: [
        {
          label: t('assessment.answers.itsOkay'),
          value: '1',
          image: 'Q13_its_okay.png',
          score: 3,
          audio: audioFiles.question_13_option_1,
        },
        {
          label: t('assessment.answers.help'),
          value: '2',
          image: 'Q13_help.png',
          score: 3,
          audio: audioFiles.question_13_option_2,
        },
        {
          label: t('assessment.answers.13_laugh'),
          value: '3',
          image: 'Q13_laugh.png',
          score: 1,
          audio: audioFiles.question_13_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '11,12,13,14.png',
    },
    {
      question: t('assessment.questions.q14'),
      questionAudio: audioFiles.question_14,
      questionId: 'question_14',
      answerOptions: [
        {
          label: t('assessment.answers.yell'),
          value: '1',
          image: 'Q14_yell.png',
          score: 1,
          audio: audioFiles.question_14_option_1,
        },
        {
          label: t('assessment.answers.breathe'),
          value: '2',
          image: 'Q14_breathe.png',
          score: 3,
          audio: audioFiles.question_14_option_2,
        },
        {
          label: t('assessment.answers.cry'),
          value: '3',
          image: 'Q14_cry.png',
          score: 2,
          audio: audioFiles.question_14_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '11,12,13,14.png',
    },
    {
      question: t('assessment.questions.q15'),
      questionAudio: audioFiles.question_15,
      questionId: 'question_15',
      answerOptions: [
        {
          label: t('assessment.answers.worried'),
          value: '1',
          image: 'Worried.png',
          score: 3,
          audio: audioFiles.question_15_option_1,
        },
        {
          label: t('assessment.answers.happy'),
          value: '2',
          image: 'Happy.png',
          score: 1,
          audio: audioFiles.question_6_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '3',
          image: 'Angry.png',
          score: 1,
          audio: audioFiles.question_6_option_2,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '15.png',
    },
    {
      type: 'story',
      question: t('assessment.stories.s3'),
      questionAudio: audioFiles.story_3,
      image: '16,17,18.png',
    },
    {
      question: t('assessment.questions.q16'),
      questionAudio: audioFiles.question_16,
      questionId: 'question_16',
      answerOptions: [
        {
          label: t('assessment.answers.worried'),
          value: '1',
          image: 'Worried.png',
          score: 3,
          audio: audioFiles.question_15_option_1,
        },
        {
          label: t('assessment.answers.happy'),
          value: '2',
          image: 'Happy.png',
          score: 1,
          audio: audioFiles.question_6_option_1,
        },
        {
          label: t('assessment.answers.angry'),
          value: '3',
          image: 'Angry.png',
          score: 2,
          audio: audioFiles.question_6_option_2,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '16,17,18.png',
    },
    {
      question: t('assessment.questions.q17'),
      questionAudio: audioFiles.question_17,
      questionId: 'question_17',
      answerOptions: [
        {
          label: t('assessment.answers.toy'),
          value: '1',
          image: 'Q17_toy.png',
          score: 3,
          audio: audioFiles.question_17_option_1,
        },
        {
          label: t('assessment.answers.13_laugh'),
          value: '2',
          image: 'Q17_laugh.png',
          score: 1,
          audio: audioFiles.question_13_option_3,
        },
        {
          label: t('assessment.answers.itsOkay'),
          value: '3',
          image: 'Q17_its_okay.png',
          score: 3,
          audio: audioFiles.question_13_option_1,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '16,17,18.png',
    },
    {
      question: t('assessment.questions.q18'),
      questionAudio: audioFiles.question_18,
      questionId: 'question_18',
      answerOptions: [
        {
          label: t('assessment.answers.shout'),
          value: '1',
          image: 'Q18_Adult.png',
          score: 1,
          audio: audioFiles.question_18_option_1,
        },
        {
          label: t('assessment.answers.breathe'),
          value: '2',
          image: 'Q18_breathe.png',
          score: 3,
          audio: audioFiles.question_14_option_2,
        },
        {
          label: t('assessment.answers.talkToAdult'),
          value: '3',
          image: 'Q18_hug.png',
          score: 3,
          audio: audioFiles.question_18_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '16,17,18.png',
    },
    {
      type: 'story',
      question: t('assessment.stories.s4'),
      questionAudio: audioFiles.story_4,
      image: '19.png',
    },
    {
      question: t('assessment.questions.q19'),
      questionAudio: audioFiles.question_19,
      questionId: 'question_19',
      answerOptions: [
        {
          label: t('assessment.answers.askAdult'),
          value: '1',
          image: 'Q19_adult.png',
          score: 3,
          audio: audioFiles.question_9_option_3,
        },
        {
          label: t('assessment.answers.share'),
          value: '2',
          image: 'Q19_share.png',
          score: 3,
          audio: audioFiles.question_19_option_2,
        },
        {
          label: t('assessment.answers.holdToy'),
          value: '3',
          image: 'Q19_hold_toy.png',
          score: 1,
          audio: audioFiles.question_19_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '19.png',
    },
    {
      type: 'story',
      question: t('assessment.stories.s5'),
      questionAudio: audioFiles.story_5,
      image: '20.png',
    },
    {
      question: t('assessment.questions.q20'),
      questionAudio: audioFiles.question_20,
      questionId: 'question_20',
      answerOptions: [
        {
          label: t('assessment.answers.askAdult'),
          value: '1',
          image: 'Q20_adult.png',
          score: 3,
          audio: audioFiles.question_9_option_3,
        },
        {
          label: t('assessment.answers.askToShare'),
          value: '2',
          image: 'Q20_ask_to_share.png',
          score: 3,
          audio: audioFiles.question_20_option_2,
        },
        {
          label: t('assessment.answers.20_hit'),
          value: '3',
          image: 'Q20_hit.png',
          score: 1,
          audio: audioFiles.question_20_option_3,
        },
        {
          label: t('assessment.answers.dontKnow'),
          value: '4',
          image: 'dont_know.png',
          score: 1,
          audio: audioFiles.question_5_option_4,
        },
      ],
      image: '20.png',
    },
    {
      question: t('assessment.questions.q21'),
      questionAudio: audioFiles.question_21,
      questionId: 'question_21',
      answerOptions: [
        {
          label: t('assessment.answers.playTablet'),
          value: 'playTablet',
          score: 1,
          image: 'Q21_play_tablet.png',
          audio: audioFiles.question_21_option_1,
        },
        {
          label: t('assessment.answers.watchVideos'),
          value: 'watchVideos',
          score: 2,
          image: 'Q21_watch_videos.png',
          audio: audioFiles.question_21_option_2,
        },
        {
          label: t('assessment.answers.watchTV'),
          value: 'watchTV',
          score: 3,
          image: 'Q21_watch_tv.png',
          audio: audioFiles.question_21_option_3,
        },
        {
          label: t('assessment.answers.watchTVWithFamily'),
          value: 'watchTVWithFamily',
          score: 4,
          image: 'Q21_watch_tv_with_fam.png',
          audio: audioFiles.question_21_option_4,
        },
        {
          label: t('assessment.answers.playSiblingOutside'),
          value: 'playSiblingOutside',
          score: 5,
          image: 'Q21_play_sibling_outside.png',
          audio: audioFiles.question_21_option_5,
        },
        {
          label: t('assessment.answers.read'),
          value: 'read',
          score: 6,
          image: 'Q21_read.png',
          audio: audioFiles.question_21_option_6,
        },
        {
          label: t('assessment.answers.playAloneOutside'),
          value: 'playAloneOutside',
          score: 7,
          image: 'Q21_play_alone_outside.png',
          audio: audioFiles.question_21_option_7,
        },
      ],
    },
  ]
}

export default getQuestions
